### PR TITLE
Format menu styling fixes

### PR DESCRIPTION
**Pull request by mmarkauskas**

### CODE REVIEW

**Review by PauliusKu — APPROVED** [review]
Tested, ok.

**Review by abelzis — APPROVED** [review]
Next time, when changing the UI, let's add screenshots for the changes

**Review by abelzis — CHANGES_REQUESTED** [review]
Why is the checkmark barely visible? Make it the same color as the text.
image

Did you change the sizes? It looks as big as it was before. What offsets, is that the menu size is waaay greater than the button size. Make the text 1.4em. and the icon fontsize to small.

To change the styles for ListItemText: https://stackoverflow.com/questions/51801916/material-ui-how-to-change-fontsize-in-lists

**Comment by mmarkauskas** [comment]
Updated.

**Review by abelzis — APPROVED** [review]

**Pull request merged**
