### PR TITLE
267 save query window configuration 1

### PR DESCRIPTION
**Pull request by MatasVGTU**

### CODE REVIEW

**Comment by PauliusKu** [comment]
@MatasVGTU add more info

**Comment by MatasVGTU** [comment]
When vscode.postMessage(obj) is executed in Fields.tsx 

src/webview/FieldsViewProvider.ts receives message and excutes
case CommandAction.LoadSavedRows:
it writes some data inside a singleton class property.

The problem is that in Fields.tsx after vscode.post there is 
const data = preferedTablesManagerHelper.getSelectedRows(); Function always returns empty because there is no way to wait for vscode.postMessage(obj) to finish. And yet it pulls singleton class property which has not been already set.

**Comment by PauliusKu** [comment]
> When vscode.postMessage(obj) is executed in Fields.tsx
> 
> src/webview/FieldsViewProvider.ts receives message and excutes case CommandAction.LoadSavedRows: it writes some data inside a singleton class property.
> 
> The problem is that in Fields.tsx after vscode.post there is const data = preferedTablesManagerHelper.getSelectedRows(); Function always returns empty because there is no way to wait for vscode.postMessage(obj) to finish. And yet it pulls singleton class property which has not been already set.

Ok, thanks, I will have a look at this issue.

**Comment by PauliusKu** [comment]
new PR https://github.com/BalticAmadeus/ProBro/pull/301

**Pull request closed without merging**
